baseURL = 'https://rhasanm.github.io/data-engineering-zoomcamp'
languageCode = 'en-us'
title = 'Data Engineer ZooCamp 2024'

theme='github.com/McShelby/hugo-theme-relearn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]
